services:
  fmi-downloader:
    image: ghcr.io/fmidev/opendata-radar-downloader:main
    build: .
    volumes:
      - ./data/fmi:/data
    environment:
      - SOURCE=fmi
      - OUTPUT_DIR=/data
    restart: unless-stopped

  metno-downloader:
    image: ghcr.io/fmidev/opendata-radar-downloader:main
    build: .
    volumes:
      - ./data/metno:/data
    environment:
      - SOURCE=metno
      - OUTPUT_DIR=/data
    restart: unless-stopped

  smhi-downloader:
    image: ghcr.io/fmidev/opendata-radar-downloader:main
    build: .
    volumes:
      - ./data/smhi:/data
    environment:
      - SOURCE=smhi
      - OUTPUT_DIR=/data
    restart: unless-stopped
